name: Build iOS IPA

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build and export IPA
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Generate Xcode Project
        working-directory: RoflCamera-iOS
        run: xcodegen generate

      - name: Build unsigned archive
        working-directory: RoflCamera-iOS
        run: |
          xcodebuild -project RoflCam.xcodeproj \
            -scheme RoflCam  \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath $PWD/build/RoflCam.xcarchive \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            archive

      - name: Export Payload to IPA
        working-directory: RoflCamera-iOS
        run: |
          mkdir -p Payload
          cp -r build/RoflCam.xcarchive/Products/Applications/RoflCam.app Payload/
          zip -qr RoflCam.ipa Payload
          
      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: RoflCam
          path: RoflCamera-iOS/RoflCam.ipa
